# Generated by Django 2.2.3 on 2019-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_address_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fulladdress',
            field=models.CharField(default='some address', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='gps',
            field=models.CharField(max_length=100),
        ),
    ]
