# Generated by Django 2.2.3 on 2019-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190713_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='gps',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.000000, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.000000, max_digits=9),
            preserve_default=False,
        ),
    ]
