# Generated by Django 2.2.3 on 2019-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190714_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='txtfile',
            field=models.FileField(blank=True, null=True, upload_to='txtfiles/'),
        ),
    ]
