# Generated by Django 2.2.3 on 2019-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_address_txtfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtfile', models.FileField(blank=True, null=True, upload_to='txtfiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='txtfile',
        ),
    ]
